import { useState, useEffect, useCallback } from 'react';
import {
  Receipt, Search, Printer, Eye, X,
  Clock, CheckCircle, RefreshCw, ShoppingBag, Utensils, Truck
} from 'lucide-react';
import api from '../../services/api';
import { showToast } from '../../components/Toast';

const formatRs = (n) => `Rs. ${(n || 0).toLocaleString('en-PK')}`;

export default function Receipts() {
  const [receipts, setReceipts] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);

  const [activeReceipt, setActiveReceipt] = useState(null);

  const fetchReceipts = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get('/reception/receipts', { params: { search, page, limit: 25 } });
      setReceipts(res.data.data || []);
      setTotal(res.data.total || 0);
    } catch (err) {
      showToast('Failed to load receipts archive.', 'error');
    } finally {
      setLoading(false);
    }
  }, [search, page]);

  useEffect(() => {
    fetchReceipts();
  }, [fetchReceipts]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fade-in" style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      {/* Top Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 }}>
        <div>
          <h1 style={{ fontSize: 22, fontWeight: 800, color: 'var(--text-primary)' }}>
            Receipts Archive
          </h1>
          <p style={{ fontSize: 13, color: 'var(--text-muted)', marginTop: 2 }}>
            Instant thermal receipt preview and reprint without creating duplicate orders.
          </p>
        </div>

        <button type="button" className="btn btn-secondary btn-sm" onClick={fetchReceipts}>
          <RefreshCw size={14} /> Refresh
        </button>
      </div>

      {/* Unified Receipts Card */}
      <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
        <div className="card-toolbar">
          <div style={{ position: 'relative', width: '100%' }}>
            <Search size={16} style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} />
            <input
              type="text"
              className="form-control"
              style={{ paddingLeft: 36 }}
              placeholder="Search receipt by Order #, Customer, Phone..."
              value={search}
              onChange={e => { setSearch(e.target.value); setPage(1); }}
            />
          </div>
        </div>

        <div className="table-container">
          {loading ? (
            <div className="loading-overlay"><div className="spinner" /></div>
          ) : receipts.length === 0 ? (
            <div className="empty-state">
              <Receipt size={40} />
              <h3>No receipts found</h3>
              <p>Receipts generated by front desk or customer orders will appear here.</p>
            </div>
          ) : (
            <table className="table">
              <thead>
                <tr>
                  <th>Receipt / Order #</th>
                  <th>Date & Time</th>
                  <th>Customer</th>
                  <th>Order Type</th>
                  <th>Items Count</th>
                  <th>Grand Total</th>
                  <th>Payment</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {receipts.map(r => (
                  <tr key={r._id}>
                    <td>
                      <span style={{ fontWeight: 800, color: 'var(--accent)' }}>{r.orderNumber}</span>
                    </td>
                    <td style={{ fontSize: 12, color: 'var(--text-muted)' }}>
                      {new Date(r.createdAt).toLocaleString()}
                    </td>
                    <td>
                      <div style={{ fontWeight: 600 }}>{r.customer?.name}</div>
                      <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{r.customer?.phone}</div>
                    </td>
                    <td>
                      <span style={{ textTransform: 'capitalize', fontWeight: 600, fontSize: 12 }}>
                        {r.orderType === 'dineIn' ? (
                          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                            <Utensils size={12} /> Table {r.tableNumber || '1'}
                          </span>
                        ) : r.orderType === 'pickup' ? (
                          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                            <ShoppingBag size={12} /> Takeaway
                          </span>
                        ) : (
                          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                            <Truck size={12} /> Delivery
                          </span>
                        )}
                      </span>
                    </td>
                    <td>{r.items?.length || 0} items</td>
                    <td style={{ fontWeight: 800 }}>
                      {formatRs(r.pricing?.grandTotal)}
                    </td>
                    <td>
                      <span className="badge badge-green">{r.paymentMethod} ({r.paymentStatus || 'Paid'})</span>
                    </td>
                    <td>
                      <div style={{ display: 'flex', gap: 6 }}>
                        <button
                          type="button"
                          className="btn btn-secondary btn-sm"
                          onClick={() => setActiveReceipt(r)}
                        >
                          <Printer size={13} /> Reprint
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>

      {/* ── Receipt View & Print Modal ── */}
      {activeReceipt && (
        <div className="modal-overlay" onClick={() => setActiveReceipt(null)}>
          <div className="modal" style={{ maxWidth: 440 }} onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h2 className="modal-title">Receipt #{activeReceipt.orderNumber}</h2>
              <div style={{ display: 'flex', gap: 8 }}>
                <button className="btn btn-primary btn-sm" onClick={handlePrint}>
                  <Printer size={14} /> Print
                </button>
                <button className="btn-icon btn-sm" onClick={() => setActiveReceipt(null)}><X size={16} /></button>
              </div>
            </div>
            <div className="modal-body" style={{ padding: '12px 24px 20px' }}>
              <div className="pos-receipt">
                <div className="pos-receipt-header">
                  <h2>UrbanBite</h2>
                  <div style={{ fontSize: 11 }}>Front Desk Order Receipt</div>
                  <div style={{ fontSize: 10, color: '#555', marginTop: 4 }}>
                    {activeReceipt.restaurant?.name || 'UrbanBite Restaurant'}
                  </div>
                </div>

                <div className="pos-receipt-row">
                  <span>Order #</span>
                  <span style={{ fontWeight: 'bold' }}>{activeReceipt.orderNumber}</span>
                </div>
                <div className="pos-receipt-row">
                  <span>Date</span>
                  <span>{new Date(activeReceipt.createdAt).toLocaleString('en-GB', {
                    day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit'
                  })}</span>
                </div>
                <div className="pos-receipt-row">
                  <span>Type</span>
                  <span style={{ textTransform: 'capitalize' }}>
                    {activeReceipt.orderType === 'dineIn' ? `Dine-In (Table ${activeReceipt.tableNumber || '1'})` : activeReceipt.orderType}
                  </span>
                </div>
                <div className="pos-receipt-row">
                  <span>Customer</span>
                  <span>{activeReceipt.customer?.name}</span>
                </div>
                <div className="pos-receipt-row">
                  <span>Phone</span>
                  <span>{activeReceipt.customer?.phone}</span>
                </div>
                <div className="pos-receipt-row">
                  <span>Payment</span>
                  <span>{activeReceipt.paymentMethod}</span>
                </div>

                <hr className="pos-receipt-divider" />

                <div style={{ marginBottom: 6, fontWeight: 'bold', display: 'flex', justifyContent: 'space-between' }}>
                  <span>Item</span><span>Amount</span>
                </div>
                {activeReceipt.items?.map((item, i) => (
                  <div key={i} style={{ marginBottom: 4 }}>
                    <div className="pos-receipt-row">
                      <span style={{ flex: 1, paddingRight: 8 }}>{item.name} × {item.quantity}</span>
                      <span>{formatRs(item.price * item.quantity)}</span>
                    </div>
                  </div>
                ))}

                <hr className="pos-receipt-divider" />

                <div className="pos-receipt-row">
                  <span>Subtotal</span>
                  <span>{formatRs(activeReceipt.pricing?.subtotal)}</span>
                </div>
                {activeReceipt.pricing?.discount > 0 && (
                  <div className="pos-receipt-row">
                    <span>Discount</span>
                    <span>- {formatRs(activeReceipt.pricing?.discount)}</span>
                  </div>
                )}
                <div className="pos-receipt-row">
                  <span>GST (5%)</span>
                  <span>{formatRs(activeReceipt.pricing?.tax)}</span>
                </div>
                {activeReceipt.pricing?.deliveryFee > 0 && (
                  <div className="pos-receipt-row">
                    <span>Delivery</span>
                    <span>{formatRs(activeReceipt.pricing?.deliveryFee)}</span>
                  </div>
                )}

                <div className="pos-receipt-total">
                  <span>TOTAL</span>
                  <span>{formatRs(activeReceipt.pricing?.grandTotal)}</span>
                </div>

                <div className="pos-receipt-footer">
                  <div>Thank you for choosing UrbanBite!</div>
                  {activeReceipt.pickupCode && (
                    <div style={{ marginTop: 6, fontWeight: 'bold', fontSize: 13 }}>
                      Pickup Code: {activeReceipt.pickupCode}
                    </div>
                  )}
                  <div style={{ fontSize: 10, color: '#555', marginTop: 4 }}>
                    Reprinted via Reception Portal
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
